runtime: php55
api_version: 1
threadsafe: yes

handlers:
  - url: /(.+\.(gif|png|jpg|css|otf|eot|svg|ttf|woff|js|ico))$
    application_readable: true
    static_files: \1
    upload: .+\.(gif|png|jpg|css|otf|eot|svg|ttf|woff|js|ico)$
  - url: /(.+\.php)$
    script: \1
  - url: /
    application_readable: true
    static_files: index.html
    upload: index.html

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
